name: Hello

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        run: echo "hello github actions"
      - name: echo hello again
        run: |
          node -v
          npm -v
      - name: python 
        shell: python
        run: |
          import platform
          print(platform.processor())
  use-action:
    runs-on: ubuntu-latest
    steps:
      - name: call other actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Richie
      - name: show action result
        run: echo "${{ steps.greet.outputs.time }}"
